#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# thoralf
/usr/bin/fbsetbg -l
# exec fluxbox
# exec fluxbox -log "/home/thoralf/.fluxbox/log"

/usr/bin/fluxbox &
fbpid=$!

sleep 1
{
    /usr/bin/compton --backend glx --paint-on-overlay --vsync opengl-swc &
    /usr/bin/gkrellm -w &
    sleep 1 && /usr/bin/wmctrl -r :ACTIVE: -e 0,0,0,500,300
    ~/kmt-synchro/start_pd_audio.sh &
    sleep 3
    ~/kmt-synchro/start_pd_video.sh &
    /usr/bin/xset -dpms; /usr/bin/xset s off
    /usr/bin/xdotool mousemove 10 10
} &
wait $fbpid
# 

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/thoralf/.fluxbox/log"
